FROM centos:6
COPY ./hosts /etc/hosts
ENV PASSWORD def456..
RUN echo $PASSWORD | passwd root --stdin 
RUN yum install openssh-clients openssh-server yum-utils createrepo curl httpd -y
COPY ./sshd_config /etc/ssh/
RUN curl https://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/cloudera-cdh5.repo > /etc/yum.repos.d/cloudera-cdh5.repo && mkdir /tmp/repo/ && reposync -p /tmp/repo -r cloudera-cdh5 && mkdir -p /var/www/html/cdh/5/ && mv /tmp/repo/cloudera-cdh5/RPMS/ /var/www/html/cdh/5/ && createrepo /var/www/html/cdh/5/
ENTRYPOINT service httpd restart && bash
